export const standardCompanyCollections = [
  {
    id: '1',
    client: 'Condomínio Jardim Europa',
    avatar: '/avatars/condominio1.jpg',
    status: 'Agendada',
    quantity: '800kg',
    material: 'Plástico e Papelão',
    date: '2024-07-15',
    time: '09:00',
    address: 'Rua das Acácias, 100 - Jardim Europa, São Paulo/SP',
    driver: 'Carlos Silva',
    cancelReason: '',
  },
  {
    id: '2',
    client: 'Shopping Central',
    avatar: '/avatars/shopping1.jpg',
    status: 'Em Andamento',
    quantity: '1200kg',
    material: 'Vidro',
    date: '2024-07-15',
    time: '11:00',
    address: 'Avenida Paulista, 2000 - Bela Vista, São Paulo/SP',
    driver: 'Fernanda Lima',
    cancelReason: '',
  },
  {
    id: '3',
    client: 'Hospital Vida Nova',
    avatar: '/avatars/hospital1.jpg',
    status: 'Concluída',
    quantity: '500kg',
    material: 'Resíduos Hospitalares',
    date: '2024-07-14',
    time: '14:00',
    address: 'Rua Saúde, 300 - Saúde, São Paulo/SP',
    driver: 'João Pereira',
    cancelReason: '',
  },
  {
    id: '4',
    client: 'Fábrica EcoTech',
    avatar: '/avatars/fabrica1.jpg',
    status: 'Agendada',
    quantity: '950kg',
    material: 'Metal',
    date: '2024-07-16',
    time: '08:00',
    address: 'Rodovia Verde, km 15 - Distrito Industrial, São Paulo/SP',
    driver: 'Carlos Silva',
    cancelReason: '',
  },
  {
    id: '5',
    client: 'Universidade Sustentável',
    avatar: '/avatars/universidade1.jpg',
    status: 'Concluída',
    quantity: '300kg',
    material: 'Eletrônicos',
    date: '2024-07-13',
    time: '10:30',
    address: 'Avenida do Saber, 500 - Cidade Universitária, São Paulo/SP',
    driver: 'Fernanda Lima',
    cancelReason: '',
  },
]; 